/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitbucket_cowwoc_requirements_diff_string_Terminal */

#ifndef _Included_org_bitbucket_cowwoc_requirements_diff_string_Terminal
#define _Included_org_bitbucket_cowwoc_requirements_diff_string_Terminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitbucket_cowwoc_requirements_diff_string_Terminal
 * Method:    stdoutIsTerminal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_bitbucket_cowwoc_requirements_diff_string_Terminal_stdoutIsTerminal
  (JNIEnv *, jobject);

/*
 * Class:     org_bitbucket_cowwoc_requirements_diff_string_Terminal
 * Method:    start
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_bitbucket_cowwoc_requirements_diff_string_Terminal_start
  (JNIEnv *, jobject);

/*
 * Class:     org_bitbucket_cowwoc_requirements_diff_string_Terminal
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_bitbucket_cowwoc_requirements_diff_string_Terminal_stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
