/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal */

#ifndef _Included_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
#define _Included_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
 * Method:    isConnectedToStdout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL
  Java_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal_isConnectedToStdout
  (JNIEnv *, jobject);

/*
 * Class:     com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
 * Method:    setEncoding
 * Signature: (Lcom/github/cowwoc/requirements/natives/terminal/TerminalEncoding;)V
 */
JNIEXPORT void JNICALL
  Java_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal_setEncoding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
  Java_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL
  Java_com_github_cowwoc_requirements_natives_internal_terminal_NativeTerminal_disconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
